name: Build and deploy the website
on: [push]
jobs:
    build:
        name: Build Gatsby project
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: yarn

            - name: Install Yarn dependencies
              run: yarn install --immutable

            - name: Gatsby .cache folder cache
              id: cache-gatsby-cache
              uses: actions/cache@v5
              with:
                  path: .cache
                  key: ${{ runner.os }}-gatsby-cache

            - name: Gatsby public folder cache
              id: cache-gatsby-public
              uses: actions/cache@v5
              with:
                  path: public
                  key: ${{ runner.os }}-gatsby-public

            - name: Build Gatsby page
              run: yarn build

            - name: Save build output
              uses: actions/upload-artifact@v7
              with:
                  name: gatsby-build-out
                  path: public
    deploy:
        name: Deploy static website to S3
        if: github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Restore build output
              uses: actions/download-artifact@v8
              with:
                  name: gatsby-build-out
                  path: public

            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Upload to AWS S3
              run: aws s3 sync public s3://portfolio.jarne.rocks --delete
